# Common configuration for both local and cloud deployments
experiment_name: "claims_status"
model_name: "claims_status_classifier"
artifact_path: "models_mlflow"

modelling_data_path: "data/insurance_claims_data.csv"
reference_data_path: "data/reference.parquet"
scored_data_path_prefix: "data/scored_dataset"
target: "claim_status"

bucket_name: "mlflow-artifacts-remote-claims"
prefect_block_aws: "mlops-aws-creds"
prefect_block_s3: "mlops-s3-bucket"
profile_name: "mlops-user"

deployment:
  local:
    mlflow_tracking_uri: "http://127.0.0.1:5000"
  cloud:
    mlflow_tracking_uri: "http://ec2-13-221-77-96.compute-1.amazonaws.com:5000"

# TODO: set to False for final training
quick_train: True