channels:
- conda-forge
dependencies:
- python=3.12.10
- pip<=25.1.1
- pip:
  - mlflow==3.1.0
  - numpy==2.3.2
  - pandas==2.3.0
  - psutil==7.0.0
  - scikit-learn==1.7.0
  - scipy==1.16.1
  - xgboost==3.0.2
name: mlflow-env
